% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL

% Sample Data Sets Avaiable in Matlab for Model Training 
% https://www.mathworks.com/help/deeplearning/gs/deep-learning-toolbox-sample-data-sets.html


% This script used Breast cancer dataset
A =heartdiseasedata';
inputs =A(1:13,:);
targets =A(14,:);

% Create a Pattern Recognition Neural Network
% Construct a multilayer feedforward neural network
% Two hidden layers, the 1st hidden layger has 10 hidden unit
% the 2nd hidden layer has 20 hidden unit
hiddenLayerSize = [10 20]; 
net = patternnet(hiddenLayerSize);
% visualize the constructed neural network
view(net); 

% Set up Division of Data for Training, Validation, Testing
% More Information on Training, Validation, Testing: 
% https://towardsdatascience.com/train-validation-and-test-sets-72cb40cba9e7
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
rng('default'); 
[net,tr] = train(net,inputs,targets);

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs)
 
% Plot Confusion Matrix
figure, plotconfusion(targets,outputs)

% Plot Network Performance for Training, Validation, Testing
figure, plotperform(tr)
 
 